import React, { useState, useEffect } from 'react';
import { NextPage } from 'next';
import Head from 'next/head';
import styles from '../styles/Home.module.css';
import Loader from './Loader';
import Login from './Login';

const Home: NextPage = () => {
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    // Simulate a delay of 5 seconds for the loader
    const loaderTimeout = setTimeout(() => {
      setLoading(false);
    }, 3000);

    // Clean up the timeout when the component unmounts or when loading state changes
    return () => {
      clearTimeout(loaderTimeout);
    };
  }, []);

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {loading ? (
        <Loader />
      ) : (
        <Login />
      )}
    </div>
  );
};

export default Home;
